### ISSUE TITLE
Implement functionality to retrieve event logs via json-rpc endpoint

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/eth-fun#17]
Consider the following address: https://etherscan.io/address/0xbbd33afa85539fa65cc08a2e61a001876d2f13fe where we specifically like to track the "Start Order" events e.g. this one: https://etherscan.io/tx/0x231a00b46517e6a53c5a05f7c2053319d610ef25f7066e1f90434aaa353f40e4

To complete this issue: implement an RPC method to retrieve event logs from an Ethereum full node using the JSON-RPC endpoint. Implement this in accordance to e.g. how "eth_call" was already implemented in the library.

**Comment by il3ven** [comment]
I was gathering information to implement this feature. Do we need to implement the [eth_newFilter](https://openethereum.github.io/JSONRPC-eth-module#eth_newfilter) and [eth_getFilterChanges](https://openethereum.github.io/JSONRPC-eth-module#eth_getfilterchanges) RPC calls?

Using the above two calls we can track the OrderStarted event.

**Comment by TimDaub** [comment]
Thanks for asking. Those are interesting questions.

As is also outlined in the readme, I heavily favor approaches that don't produce a shared state between the RPC endpoint and our client. For `eth_newFilter` and `eth_getFilterChanges`, however, I can see that somehow a shared state has to get persisted on the RPC node and I don't like it.

Rather, I think the client should own the state. I've found that `[eth_getLogs](https://eth.wiki/json-rpc/API#eth_getlogs)` allows us to do that. E.g. for crawling in rugpullindex.com, I could now imagine going block by block and asking for the "OrderStarted" event from the block of the contract's creation.

**Comment by il3ven** [comment]
`eth_getLogs` will also work. 👍🏽 

May I ask, what's the problem with having a shared state on the RPC node?

**Comment by TimDaub** [comment]
> May I ask, what's the problem with having a shared state on the RPC node?

In distributed systems, the shared state adds complexity as suddenly code becomes unpredictable. It's hard to reason and hard to test. For a remotely shared state, suddenly you have to think in terms of two separate computers and a wire between them. In our case there are several drawbacks to shared state, e.g.:

- We don't know how the shared state of our Erigon node behaves and how it's implemented
- We don't control the shared state Erigon runtime; so even if e.g. we're aware of a mistake on our remote RPC node we might not be able to "fix" it
- It's unclear how we can parallelize a shared state remote execution. If we use `eth_getLogs` we know all blocks, events, and contracts we want to crawl and we can schedule the crawling ourselves. However, when we use a shared state approach, we have limited control over parallelization: We probably have to rely on the Erigon node.
- Then there are known unknowns:
  - What happens to shared state requests in cases where e.g. a connection is dropped?
  - Can there be race conditions?
  - etc.
