### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by il3ven** [rugpullindex/eth-fun#19]
The current bundle includes all the  node_modules library. Thus, its size is big (~20MB). As a result the npm library size also increases.

![image](https://user-images.githubusercontent.com/4337699/133439164-0ef82fad-5877-4496-b042-cac47087ad13.png)

## Proposal

Bundling all the node_modules libraries seem redundant for node packages. Since `npm install eth-fun` will anyway install all the dependencies. Bundling makes sense for browsers.

I think we should export the files in `src/` without any bundling. These will be the exported as an ES module. For dual support, we can transpile the current files in `src/` to commonJS and put them in the `cjs/`.

The `package.json` will look somewhat similar to this.
```js
{
  "exports": {
    ".": {
      "require": "./cjs/index.js"
      "default": "./src/index.js"
     }
  }
}
  
```

**Comment by TimDaub** [comment]
Sounds good 👍🏼
