### ISSUE TITLE
Implement connection pool

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/eth-fun#23]
When using eth-fun as a dependency in a project and e.g. the `call` method is simply used in a for loop; then eth-fun is rather slow and sequential. In the project itself; we'd like to avoid having to implement a worker pool that handles connections. Rather connecting, sending requests and managing concurrency shall be the responsibility of eth-fun. We draw this expectation from working with database drivers where usually a user can utilize a "connection pool" to introduce concurrency into i/o operations.

Similarly, then we set an expectation that eth-fun should be parallelizable. But without introducing shared state between client and server.

I've done some preliminary research into this topic and here's what I think could be done on a conceptual level:

- Introduce a queue similar to [p-queue](https://github.com/sindresorhus/p-queue)
- Export a pool property from eth-fun that, upon its instantiation, allows to draw connections from
- For all connections and their request, within eth-fun, handle their execution as concurrently as possible
- Return the request's replies similarly to right now simply as promisable returns

Additionally, it should be kept in mind that this connection pool feature ideally works both in a browser environment as well on node.js. Though given rugpullindex's current use case: we only use eth-fun on the server and so a node.js-biased implementation would be OK.

**Comment by il3ven** [comment]
> We add a section about concurrent requests and e.g. p-limit usage to e.g. the readme

I think this is what we should do now. What do you say?

> We go even further than adding p-limit by starting to give users guarantees about the requests they send, e.g. "eth-fun" will always try to maximize your json-rpc call requests. It'll e.g. try 3 times to execute a read request and only then return with an error etc.

We can do this in the future if the need for it arises.

**Comment by TimDaub** [comment]
ok fine

**Comment by il3ven** [comment]
How about I add an example in the repo that uses p-limit? We can link the example in the Readme.

**Comment by TimDaub** [comment]
👍🏼
