### ISSUE TITLE
npm engine requirement must follow node engine requirement and be less strict

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/eth-fun#43]
- see this run: https://github.com/neume-network/strategies/runs/7304571512?check_suite_focus=true

**Comment by il3ven** [comment]
Do we need a npm requirement? I think we can remove it and only keep the node requirement.

**Comment by TimDaub** [comment]
it is happening here too: https://github.com/neume-network/core/runs/7880780990?check_suite_focus=true#step:5:8
